# Generated by Django 4.0.4 on 2022-07-05 09:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_class', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=40)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Dice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dice_type', models.CharField(max_length=20)),
                ('sides', models.JSONField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_class', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=40)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_class', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=40)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_class', models.CharField(max_length=30)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('side', models.CharField(max_length=30)),
                ('unit_class', models.CharField(default='default_unit_class', max_length=30)),
                ('moves', models.IntegerField(default=2)),
                ('search_range', models.IntegerField()),
                ('speed', models.IntegerField()),
                ('max_speed', models.IntegerField(default=0)),
                ('current_speed', models.IntegerField(default=0)),
                ('health', models.IntegerField()),
                ('max_health', models.IntegerField(default=0)),
                ('current_health', models.IntegerField(default=0)),
                ('durability', models.IntegerField()),
                ('max_durability', models.IntegerField(default=0)),
                ('current_durability', models.IntegerField(default=0)),
                ('fist', models.IntegerField()),
                ('book', models.IntegerField()),
                ('shield', models.IntegerField()),
                ('eye', models.IntegerField()),
                ('x_coord', models.IntegerField(default=None, null=True)),
                ('y_coord', models.IntegerField(default=None, null=True)),
                ('actions', models.ManyToManyField(to='unit.action')),
                ('block', models.ManyToManyField(related_name='block', to='unit.dice')),
                ('current_block', models.ManyToManyField(related_name='current_block', to='unit.dice')),
                ('items', models.ManyToManyField(to='unit.item')),
                ('max_block', models.ManyToManyField(related_name='max_block', to='unit.dice')),
                ('skills', models.ManyToManyField(to='unit.skill')),
                ('statuses', models.ManyToManyField(to='unit.status')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AddSpeedForStamina',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('unit.action',),
        ),
        migrations.CreateModel(
            name='ArcaneBolt',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('unit.item',),
        ),
        migrations.CreateModel(
            name='ChippedGreataxe',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('unit.item',),
        ),
        migrations.CreateModel(
            name='DefaultAshrian',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('unit.skill',),
        ),
        migrations.CreateModel(
            name='DefaultGrisban',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('unit.skill',),
        ),
        migrations.CreateModel(
            name='DefaultLeoric',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('unit.skill',),
        ),
        migrations.CreateModel(
            name='DefaultSindrael',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('unit.skill',),
        ),
        migrations.CreateModel(
            name='Fallen',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('unit.status',),
        ),
        migrations.CreateModel(
            name='Greedy',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('unit.skill',),
        ),
        migrations.CreateModel(
            name='IronLongsword',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('unit.item',),
        ),
        migrations.CreateModel(
            name='IronMace',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('unit.item',),
        ),
        migrations.CreateModel(
            name='LuckyCharm',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('unit.item',),
        ),
        migrations.CreateModel(
            name='MoveUnit',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('unit.action',),
        ),
        migrations.CreateModel(
            name='Nimble',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('unit.skill',),
        ),
        migrations.CreateModel(
            name='OakStaff',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('unit.item',),
        ),
        migrations.CreateModel(
            name='OathOfHonor',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('unit.skill',),
        ),
        migrations.CreateModel(
            name='PickUpTreasure',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('unit.action',),
        ),
        migrations.CreateModel(
            name='Poisoned',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('unit.status',),
        ),
        migrations.CreateModel(
            name='PrayerOfHealing',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('unit.skill',),
        ),
        migrations.CreateModel(
            name='Rage',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('unit.skill',),
        ),
        migrations.CreateModel(
            name='RaiseDead',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('unit.skill',),
        ),
        migrations.CreateModel(
            name='RandomTreasure',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('unit.item',),
        ),
        migrations.CreateModel(
            name='ReapersScythe',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('unit.item',),
        ),
        migrations.CreateModel(
            name='RunicKnowledge',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('unit.skill',),
        ),
        migrations.CreateModel(
            name='Stoneskin',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('unit.skill',),
        ),
        migrations.CreateModel(
            name='Stunned',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('unit.status',),
        ),
        migrations.CreateModel(
            name='ThrowingKnives',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('unit.item',),
        ),
        migrations.CreateModel(
            name='UltraAshrian',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('unit.skill',),
        ),
        migrations.CreateModel(
            name='UltraGrisban',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('unit.skill',),
        ),
        migrations.CreateModel(
            name='UltraLeoric',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('unit.skill',),
        ),
        migrations.CreateModel(
            name='UltraSindrael',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('unit.skill',),
        ),
        migrations.CreateModel(
            name='WoodenShield',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('unit.item',),
        ),
        migrations.CreateModel(
            name='YewShortbow',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('unit.item',),
        ),
    ]
