# Generated by Django 4.0.4 on 2022-07-05 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lobby', '0001_initial'),
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='lobby',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lobby.lobby'),
        ),
        migrations.AddField(
            model_name='game',
            name='map',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='game.map'),
        ),
    ]
