# Generated by Me on 2022-07-05 14:34
from django.contrib.auth.models import User
from django.db import migrations, models
from game.models import MapTemplate
import json


def map_templates(apps, schema):
    model = apps.get_model('game', 'MapTemplate')
    model.objects.all().delete()
    MapTemplate.objects.create(
        name='first_blood_dev',
        map=[["S", "S", "S", "S", "S", "S", "S", "S", "S", "S", "S", "S", "S", "S", "S", "S", "S", "S", "S", "S"],
             ["S", "S", "S", "S", "S", "S", "B", "B", "B", "B", "B", "B", "S", "S", "S", "S", "S", "S", "S", "S"],
             ["S", "S", "B", "B", "B", "B", "B", "F", "F", "F", "F", "B", "S", "S", "S", "S", "S", "S", "S", "S"],
             ["S", "S", "B", "F", "F", "B", "S", "F", "F", "F", "F", "B", "S", "S", "S", "S", "S", "S", "S", "S"],
             ["S", "S", "B", "F", "F", "B", "S", "F", "F", "F", "F", "B", "S", "S", "S", "S", "S", "S", "S", "S"],
             ["S", "B", "B", "F", "F", "B", "B", "F", "F", "F", "F", "S", "B", "B", "B", "S", "S", "S", "S", "S"],
             ["S", "B", "F", "W", "W", "B", "B", "B", "F", "F", "B", "B", "F", "F", "B", "S", "S", "S", "S", "S"],
             ["S", "B", "F", "W", "W", "W", "F", "F", "F", "F", "F", "F", "F", "F", "S", "S", "S", "S", "S", "S"],
             ["S", "B", "F", "W", "W", "W", "F", "F", "F", "F", "F", "F", "F", "F", "S", "S", "S", "S", "S", "S"],
             ["S", "B", "F", "F", "F", "F", "B", "B", "F", "F", "B", "B", "F", "F", "B", "S", "S", "S", "S", "S"],
             ["S", "B", "B", "B", "B", "B", "B", "B", "F", "F", "B", "B", "B", "B", "B", "S", "S", "S", "S", "S"],
             ["S", "S", "S", "S", "S", "S", "B", "F", "F", "F", "F", "B", "S", "S", "S", "S", "S", "S", "S", "S"],
             ["S", "S", "S", "S", "S", "S", "S", "F", "F", "F", "F", "S", "S", "S", "S", "S", "S", "S", "S", "S"],
             ["S", "S", "S", "S", "S", "S", "S", "F", "F", "F", "F", "S", "S", "S", "S", "S", "S", "S", "S", "S"],
             ["S", "S", "S", "S", "S", "S", "B", "F", "F", "F", "F", "B", "S", "S", "S", "S", "S", "S", "S", "S"],
             ["S", "S", "S", "S", "S", "S", "B", "B", "B", "B", "B", "B", "S", "S", "S", "S", "S", "S", "S", "S"],
             ["S", "S", "S", "S", "S", "S", "S", "S", "S", "S", "S", "S", "S", "S", "S", "S", "S", "S", "S", "S"],
             ["S", "S", "S", "S", "S", "S", "S", "S", "S", "S", "S", "S", "S", "S", "S", "S", "S", "S", "S", "S"],
             ["S", "S", "S", "S", "S", "S", "S", "S", "S", "S", "S", "S", "S", "S", "S", "S", "S", "S", "S", "S"],
             ["S", "S", "S", "S", "S", "S", "S", "S", "S", "S", "S", "S", "S", "S", "S", "S", "S", "S", "S", "S"]],
        creator=User.objects.create(username='dev_user', email='sdf@sdf.com', password='bananana'),
        type=MapTemplate.MapTemplateType.DEVELOPER)


def map_templates_reversal(apps, schema):
    model = apps.get_model('game', 'MapTemplate')
    model.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_initial'),
    ]

    operations = [
        migrations.RunPython(map_templates, map_templates_reversal),
    ]
