# Generated by Django 4.0.4 on 2022-07-07 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_data_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='round_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='maptemplate',
            name='name',
            field=models.CharField(max_length=55),
        ),
    ]
